PR for Issue #559: Publishing components + client (#573)
this is the branch I pushed directly to eidolon rather than running it
from my fork

closes #559 

See successful GitHub Actions workflow from my fork here:
https://github.com/jahabeebs/eidolon/actions/runs/10003144677/job/27649567288

I don't have publishing rights for @eidolon/client or
@eidolon/components but as you can see in the workflow logs above if we
run it on the eidolon repo we should be able to publish versions 1.0.0

The next step would then be to enable the changeset bot for eidolon's
repo: https://github.com/apps/changeset-bot

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -2,15 +2,15 @@ name: Playwright Tests
 
 on:
   workflow_dispatch:
-#  push:
-#    branches: [main]
-#    paths:
-#      - '**'
-#      - '!k8s-operator/**'
-#  pull_request:
-#    paths:
-#      - '**'
-#      - '!k8s-operator/**'
+  push:
+    branches: [main]
+    paths:
+      - '**'
+      - '!k8s-operator/**'
+  pull_request:
+    paths:
+      - '**'
+      - '!k8s-operator/**'
 
 jobs:
   test-e2e:
@@ -38,6 +38,13 @@ jobs:
       CI: true
 
     steps:
+      - name: Check for OPENAI_API_KEY
+        run: |
+          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
+            echo "OPENAI_API_KEY is not set. Failing the job."
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v3
 
